name: EAS Test Distribution
on:
  workflow_dispatch:

jobs:
  upload-to-drive:
    name: Upload Dummy Text File to Google Drive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dummy text file
        run: |
          echo "This is a dummy text file for testing upload to Google Drive" > dummy.txt

      - uses: actions/github-script@v6
        id: set-result
        with:
          script: return "build/generated.apk"
          result-encoding: string

      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"

      - name: Authenticate with Google Drive and upload dummy file
        uses: hoatruongdev09/google-drive-file-upload-github-action@v1.1
        with:
          service-account-json: ${{ secrets.GOOGLE_CREDENTIALS }}
          upload-to-folder-id: ${{ secrets.DRIVE_FOLDER_ID }}
          upload-name: ${{ env.DYNAMIC_NAME }}
          file-path: dummy.txt
