name: EAS Internal APK Distribution
on:
  workflow_dispatch:
    platform:
      description: "Build Platform"
      required: true
      default: "android"
      type: choice
      options:
        - android
        - ios

jobs:
  app-build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: yarn

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Internal dev build
        shell: bash
        run: |
          mkdir -p build |
          eas build --profile dev-preview --platform android --local --output=build/generated.${{ github.event.inputs.platform == 'android' && 'apk' || 'ipa' }}

      - uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: build

  upload-to-drive:
    name: Upload APK to Google Drive
    runs-on: ubuntu-latest
    needs: app-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: apk-build
          path: build

      - name: Set current datetime for apk build
        shell: bash
        run: |
          datetime=$(date +'%Y-%m-%dT%H:%M:%S')
          echo "DateTime=$datetime" >> $GITHUB_ENV

      - name: Authenticate and upload to Google Drive
        uses: hoatruongdev09/google-drive-file-upload-github-action@v1.1
        with:
          service-account-json: ${{ secrets.GOOGLE_CREDENTIALS }}
          upload-to-folder-id: ${{ secrets.DRIVE_FOLDER_ID }}
          file-path: build/generated.${{ github.event.inputs.platform == 'android' && 'apk' || 'ipa' }}
          upload-name: ${{ env.DateTime }}-Journa.${{ github.event.inputs.platform == 'android' && 'apk' || 'ipa' }}
