name: EAS Test Distribution
on:
  workflow_dispatch:

jobs:
  upload-to-drive:
    name: Upload Dummy Text File to Google Drive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dummy text file
        run: |
          echo "This is a dummy text file for testing upload to Google Drive" > dummy.txt

      - name: Generate dynamic upload name
        run: |
          # Get current date and time in 'YYYY-MM-DDTHH:MM:SS' format
          CURRENT_DATETIME=$(date +'%Y-%m-%dT%H:%M:%S')

          # Construct the dynamic upload name with desired format
          DYNAMIC_NAME="${CURRENT_DATETIME}-journal.txt"

          # Print the dynamic name for reference (optional)
          echo "Dynamic Upload Name: $DYNAMIC_NAME"

      - name: Authenticate with Google Drive and upload dummy file
        uses: hoatruongdev09/google-drive-file-upload-github-action@v1.1
        with:
          service-account-json: ${{ secrets.GOOGLE_CREDENTIALS }}
          upload-to-folder-id: ${{ secrets.DRIVE_FOLDER_ID }}
          upload-name: ${{ dynamic_name }}
          file-path: dummy.txt
